apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-postgres
  labels:
    app: users-postgres
  namespace: micro
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi