apiVersion: v1
kind: Service
metadata:
  name: users-postgres
  labels:
    app: users-postgres
  namespace: micro
spec:
  ports:
    - port: 5432
  selector:
    app: users-postgres
  clusterIP: None